services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" #
    volumes:
      - .:/app # Mount the current directory to /app in the container
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
